services:
  - type: web
    name: ragentix-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10

  - type: redis
    name: ragentix-cache
    plan: free
    ipAllowList: []

databases:
  - name: ragentix-db
    plan: free
